### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by c-g-dev** [GamingLiamStudios/rxdataToJSON#2]
Failed to build with many similar errors:

error C2039: '__throw_invalid_argument': is not a member of 'std'
error C2039: '__throw_ios_failure': is not a member of 'std'
error C2065: '__DEC64_MIN__': undeclared identifier
error C2065: '__DEC64_MAX__': undeclared identifier

Using the following:

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.39.33519.0

I didn't look too deep into it, just gave this repo a cursory attempt at compiling and it didn't work. Just logging this for the info.

**Comment by GamingLiamStudios** [comment]
Very interesting. Seems like that MSVC cannot find the standard libraries on ur system. All I can really suggest is to ensure that MSVC is fully up to date, has the STL library (not sure if VS installer allows you to not include that) and that CMake is properly installed.

Closing as I'm 95% sure this is User Error with compiler configuration and not a problem with my code specifically.
